Correction du Nom + Erreur dans le code V1
pendu_cosmo_oscar(v2).py -> pendu_cosmo_oscarV2.py

> Avec les parenthèses le terminale affichaient : "zsh: no matches found: ..."

Le code pour la V1 ne marche pas pour moi. Elle affiche
..., line 54
    global mot_trouve
    ^^^^^^^^^^^^^^^^^
SyntaxError: name 'mot_trouve' is used prior to global declaration